/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio1;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author pedro.rinpiz
 */

public class FrmPrincipal extends javax.swing.JFrame {
    static int jugadas = 0;
    static int ganadas1 = 0;
    static int perdidas1 = 0;
    
    
    
    Random rd = new Random();
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        img2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        result1 = new javax.swing.JTextField();
        result2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtJugados = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGanados1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPerdidos1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGanados2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPerdidos2 = new javax.swing.JTextField();
        btJugar = new javax.swing.JButton();
        btInstrucciones = new javax.swing.JButton();
        btAcercaDe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dado 1"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dado 2"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(img2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Jugador 1");

        jLabel2.setText("Jugador 2");

        jLabel3.setText("Dado 1:");

        jLabel4.setText("Dado 2:");

        result1.setText("0");

        result2.setText("0");

        jLabel5.setText("Jugados:");

        txtJugados.setText("0");

        jLabel6.setText("Ganados:");

        txtGanados1.setText("0");

        jLabel7.setText("Perdidos:");

        txtPerdidos1.setText("0");

        jLabel9.setText("Ganados:");

        txtGanados2.setText("0");

        jLabel10.setText("Perdidos:");

        txtPerdidos2.setText("0");

        btJugar.setText("Jugar");
        btJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJugarActionPerformed(evt);
            }
        });

        btInstrucciones.setText("Instrucciones");
        btInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInstruccionesActionPerformed(evt);
            }
        });

        btAcercaDe.setText("Acerca de");
        btAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcercaDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGanados1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJugados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerdidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 132, Short.MAX_VALUE)
                                .addComponent(btJugar)
                                .addGap(45, 45, 45)
                                .addComponent(btInstrucciones)))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(result2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGanados2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPerdidos2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btAcercaDe, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(result2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtJugados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGanados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPerdidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGanados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPerdidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btJugar)
                    .addComponent(btInstrucciones)
                    .addComponent(btAcercaDe))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJugarActionPerformed
        int dado = rd.nextInt(6);
        int dado1 = dado;
        
        switch (dado) {
            case 1:
                img1.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara1.png"));
                result1.setText("1");
                break;
                
            case 2:
                img1.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara2.png"));
                result1.setText("2");
                break;
                
            case 3:
                img1.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara3.png"));
                result1.setText("3");
                break;
                
            case 4:
                img1.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara4.png"));
                result1.setText("4");
                break;
                
            case 5:
                img1.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara5.png"));
                result1.setText("5");
                break;
                
            case 6:
                img1.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara6.png"));
                result1.setText("6");
                break;
            default:
                throw new AssertionError();
        }
        
        dado = rd.nextInt(6);
        int dado2 = dado;
        
        switch (dado) {
            case 1:
                img2.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara1.png"));
                result2.setText("1");
                break;
                
            case 2:
                img2.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara2.png"));
                result2.setText("2");
                break;
                
            case 3:
                img2.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara3.png"));
                result2.setText("3");
                break;
                
            case 4:
                img2.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara4.png"));
                result2.setText("4");
                break;
                
            case 5:
                img2.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara5.png"));
                result2.setText("5");
                break;
                
            case 6:
                img2.setIcon(new ImageIcon("C:\\Users\\pedro.rinpiz\\OneDrive - Educacyl\\2º\\pc 2º\\Documentos\\NetBeansProjects\\ExamenRecuperacionInterfaces\\src\\imgs\\cara6.png"));
                result2.setText("6");
                break;
            default:
                throw new AssertionError();
        }
        
        jugadas++;
        txtJugados.setText(String.valueOf(jugadas));
        
        if(dado1 > dado2)
        {
            ganadas1++;
            txtGanados1.setText(String.valueOf(ganadas1));
            txtPerdidos2.setText(String.valueOf(ganadas1));
        }
        else if(dado2 > dado1)
        {
            perdidas1++;
            txtPerdidos1.setText(String.valueOf(perdidas1));
            txtGanados2.setText(String.valueOf(perdidas1));
        }
    }//GEN-LAST:event_btJugarActionPerformed

    private void btInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInstruccionesActionPerformed
        
    }//GEN-LAST:event_btInstruccionesActionPerformed

    private void btAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcercaDeActionPerformed
        
    }//GEN-LAST:event_btAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcercaDe;
    private javax.swing.JButton btInstrucciones;
    private javax.swing.JButton btJugar;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField result1;
    private javax.swing.JTextField result2;
    private javax.swing.JTextField txtGanados1;
    private javax.swing.JTextField txtGanados2;
    private javax.swing.JTextField txtJugados;
    private javax.swing.JTextField txtPerdidos1;
    private javax.swing.JTextField txtPerdidos2;
    // End of variables declaration//GEN-END:variables
}
