/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import clases.TablaRender;
import java.awt.Color;
import modelo.*;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.ValidarNumerico;
import utils.ValidarTexto;


public class FrmPrincipal extends javax.swing.JFrame {
    ValidarNumerico validarNumerico = new ValidarNumerico();
    ValidarTexto validarTexto = new ValidarTexto();
    
    ArrayList<Producto>  listaProductos=new ArrayList<>();
    
    String              columnas[]={"codigo","producto","precio","acción"};
    boolean             columnasEditables[]={false,false,false,true};
    Class               tipo[]=new Class[]{java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Boolean.class};
    
    DefaultTableModel modeloP=new DefaultTableModel(){
    
        @Override
        public boolean isCellEditable(int row,int col){
             return columnasEditables[col];
        }
        @Override
        public Class getColumnClass(int index){
             return tipo[index];
         }
    }; 
    public FrmPrincipal() {
        initComponents();
        inicializarTabla();
    }
    public void inicializarTabla(){
        modeloP.setColumnIdentifiers(columnas);
        JTablePersonas.setModel(modeloP);
        JTablePersonas.setDefaultRenderer(Object.class,new TablaRender());
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnDatos = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblProducto = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        pnOpciones = new javax.swing.JPanel();
        btnMostrarPrecioMedio = new javax.swing.JButton();
        btnContarProductos = new javax.swing.JButton();
        btnMostrarSeleccionados = new javax.swing.JButton();
        cbSeleccionarTodo = new javax.swing.JCheckBox();
        pnTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablePersonas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTable con Checkbox");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("MANTENIMIENTO DE PRODUCTOS");

        pnDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del producto"));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblCodigo.setText("Codigo producto:");

        lblProducto.setText("Producto:");

        lblPrecio.setText("Precio:");

        javax.swing.GroupLayout pnDatosLayout = new javax.swing.GroupLayout(pnDatos);
        pnDatos.setLayout(pnDatosLayout);
        pnDatosLayout.setHorizontalGroup(
            pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDatosLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addComponent(lblProducto)
                    .addComponent(lblPrecio))
                .addGap(25, 25, 25)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                        .addComponent(txtProducto)
                        .addComponent(txtPrecio)))
                .addGap(214, 214, 214))
        );
        pnDatosLayout.setVerticalGroup(
            pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnMostrarPrecioMedio.setText("Mostrar el Precio Medio de Todos");
        btnMostrarPrecioMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPrecioMedioActionPerformed(evt);
            }
        });

        btnContarProductos.setText("Contar el número de Productos");
        btnContarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarProductosActionPerformed(evt);
            }
        });

        btnMostrarSeleccionados.setText("Mostrar Reporte de Seleccionados");
        btnMostrarSeleccionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSeleccionadosActionPerformed(evt);
            }
        });

        cbSeleccionarTodo.setText("Seleccionar Todo");
        cbSeleccionarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeleccionarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnOpcionesLayout = new javax.swing.GroupLayout(pnOpciones);
        pnOpciones.setLayout(pnOpcionesLayout);
        pnOpcionesLayout.setHorizontalGroup(
            pnOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarPrecioMedio)
                    .addComponent(btnContarProductos)
                    .addGroup(pnOpcionesLayout.createSequentialGroup()
                        .addComponent(btnMostrarSeleccionados)
                        .addGap(18, 18, 18)
                        .addComponent(cbSeleccionarTodo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnOpcionesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnContarProductos, btnMostrarPrecioMedio, btnMostrarSeleccionados});

        pnOpcionesLayout.setVerticalGroup(
            pnOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMostrarPrecioMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnContarProductos)
                .addGap(12, 12, 12)
                .addGroup(pnOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarSeleccionados)
                    .addComponent(cbSeleccionarTodo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnOpcionesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnContarProductos, btnMostrarPrecioMedio, btnMostrarSeleccionados});

        pnTabla.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Productos"));

        JTablePersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTablePersonas);

        javax.swing.GroupLayout pnTablaLayout = new javax.swing.GroupLayout(pnTabla);
        pnTabla.setLayout(pnTablaLayout);
        pnTablaLayout.setHorizontalGroup(
            pnTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnTablaLayout.setVerticalGroup(
            pnTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTabla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(pnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       txtCodigo.setBorder(null);
       txtProducto.setBorder(null);
       txtPrecio.setBorder(null);
        
        boolean valido = false;
        if(validarNumerico.validarEntero(txtCodigo.getText())  && validarTexto.esValido(txtProducto.getText()) && validarNumerico.validarDouble(txtPrecio.getText())) valido = true;
        if(validarNumerico.validarEntero(txtCodigo.getText()) == false) txtCodigo.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        if(validarTexto.esValido(txtProducto.getText()) == false) txtProducto.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        if(validarNumerico.validarDouble(txtPrecio.getText()) == false) txtPrecio.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        
        if(valido){
            listaProductos.add(new Producto(Integer.parseInt(txtCodigo.getText()),txtProducto.getText(),Double.parseDouble(txtPrecio.getText()),false));

            Object lineaPer[]={txtCodigo.getText(),txtProducto.getText(),txtPrecio.getText(),false};
            modeloP.addRow(lineaPer);
           
            txtCodigo.setText("");
            txtProducto.setText("");
            txtPrecio.setText("");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMostrarSeleccionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSeleccionadosActionPerformed
        // TODO add your handling code here:
        String seleccionados = "";
        for(Producto pro : listaProductos){
            if(pro.isAccion()) seleccionados += pro.toString() + "\n";
        }
        JOptionPane.showMessageDialog(this, "Los productos seleccionados son:\n" + seleccionados);
    }//GEN-LAST:event_btnMostrarSeleccionadosActionPerformed

    private void btnContarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarProductosActionPerformed
        // TODO add your handling code here:
        int numProductos = listaProductos.size();
        JOptionPane.showMessageDialog(this, "El número de productos es:\n" + numProductos);
    }//GEN-LAST:event_btnContarProductosActionPerformed

    private void btnMostrarPrecioMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPrecioMedioActionPerformed
        // TODO add your handling code here:
        int contador = 0;
        double total = 0;
        for(Producto pro : listaProductos){
            contador++;
            total += pro.getPrecio();
        }
        
        double media = total/contador;
        JOptionPane.showMessageDialog(this, "El precio medio de los productos es:\n" + media);
    }//GEN-LAST:event_btnMostrarPrecioMedioActionPerformed

    private void cbSeleccionarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeleccionarTodoActionPerformed
        // TODO add your handling code here:
        if(cbSeleccionarTodo.isSelected()){
            modeloP = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row,int col){
                     return columnasEditables[col];
                }
                @Override
                public Class getColumnClass(int index){
                     return tipo[index];
                 }
            }; 
            inicializarTabla();
            for(Producto pro : listaProductos){
                Object lineaPer[]={String.valueOf(pro.getCodProducto()),pro.getProducto(),String.valueOf(pro.getPrecio()), true};
                modeloP.addRow(lineaPer);
            }
            cbSeleccionarTodo.setText("Deseleccionar Todo");
        }
        else{
            modeloP = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row,int col){
                     return columnasEditables[col];
                }
                @Override
                public Class getColumnClass(int index){
                     return tipo[index];
                 }
            }; 
            inicializarTabla();
            for(Producto pro : listaProductos){
                Object lineaPer[]={String.valueOf(pro.getCodProducto()),pro.getProducto(),String.valueOf(pro.getPrecio()), false};
                modeloP.addRow(lineaPer);
            }
            cbSeleccionarTodo.setText("Seleccionar Todo");
        }
    }//GEN-LAST:event_cbSeleccionarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablePersonas;
    private javax.swing.JButton btnContarProductos;
    private javax.swing.JButton btnMostrarPrecioMedio;
    private javax.swing.JButton btnMostrarSeleccionados;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox cbSeleccionarTodo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnDatos;
    private javax.swing.JPanel pnOpciones;
    private javax.swing.JPanel pnTabla;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
