/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio2;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adrian.veldie.2
 */
public class Formulario extends javax.swing.JFrame {

    ArrayList<Producto> arrayListProd = new ArrayList<>();

    String columnas[] = {"Codigo", "Producto", "Precio", "Accion"};
    boolean columnasEditables[] = {false, false, false, true};
    Class tipo[] = new Class[]{java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class};

    DefaultTableModel modeloTabla = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int col) {
            return columnasEditables[col];
        }

        @Override
        public Class getColumnClass(int index) {
            return tipo[index];
        }
    };

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        setTitle("Mantenimiento de Productos");
        setLocationRelativeTo(null);

        modeloTabla.setColumnIdentifiers(columnas);
        jTable1.setModel(modeloTabla);
        jTable1.setDefaultRenderer(Object.class, new TablaRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnDatosProd = new javax.swing.JPanel();
        lblDatosProd = new javax.swing.JLabel();
        lblCodProd = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        txtProd = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnResgistrar = new javax.swing.JButton();
        pnOpciones = new javax.swing.JPanel();
        lblOpciones = new javax.swing.JLabel();
        btnPrecioMedio = new javax.swing.JButton();
        btnNumProd = new javax.swing.JButton();
        btnMostrarSeleccionados = new javax.swing.JButton();
        jCheckBoxTodo = new javax.swing.JCheckBox();
        pnProductos = new javax.swing.JPanel();
        lblListaProd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnPrincipal.setBackground(new java.awt.Color(204, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("MANTENIMIENTO DE PRODUCTOS");

        lblDatosProd.setText("Datos del producto");

        lblCodProd.setText("Codigo producto: ");

        lblProducto.setText("Producto:");

        jLabel1.setText("Precio:");

        btnResgistrar.setText("Registrar");
        btnResgistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResgistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDatosProdLayout = new javax.swing.GroupLayout(pnDatosProd);
        pnDatosProd.setLayout(pnDatosProdLayout);
        pnDatosProdLayout.setHorizontalGroup(
            pnDatosProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDatosProdLayout.createSequentialGroup()
                .addGroup(pnDatosProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDatosProdLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblDatosProd))
                    .addGroup(pnDatosProdLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnDatosProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodProd)
                            .addComponent(lblProducto)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(pnDatosProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodProd)
                            .addComponent(txtProd)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(btnResgistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnDatosProdLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, lblCodProd, lblProducto});

        pnDatosProdLayout.setVerticalGroup(
            pnDatosProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDatosProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDatosProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProd)
                    .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDatosProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDatosProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnResgistrar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnDatosProdLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, lblCodProd, lblProducto});

        lblOpciones.setText("Opciones");

        btnPrecioMedio.setText("Mostrar el Precio Medio de Todos");
        btnPrecioMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecioMedioActionPerformed(evt);
            }
        });

        btnNumProd.setText("Contar el numero de Productos");
        btnNumProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumProdActionPerformed(evt);
            }
        });

        btnMostrarSeleccionados.setText("Mostrar Reporte de Seleccionados");
        btnMostrarSeleccionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSeleccionadosActionPerformed(evt);
            }
        });

        jCheckBoxTodo.setText("Seleccionar Todo");
        jCheckBoxTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnOpcionesLayout = new javax.swing.GroupLayout(pnOpciones);
        pnOpciones.setLayout(pnOpcionesLayout);
        pnOpcionesLayout.setHorizontalGroup(
            pnOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOpcionesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrecioMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnOpcionesLayout.createSequentialGroup()
                        .addComponent(btnMostrarSeleccionados)
                        .addGap(51, 51, 51)
                        .addComponent(jCheckBoxTodo))
                    .addComponent(btnNumProd)
                    .addComponent(lblOpciones))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        pnOpcionesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMostrarSeleccionados, btnNumProd, btnPrecioMedio});

        pnOpcionesLayout.setVerticalGroup(
            pnOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOpcionesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblOpciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrecioMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNumProd)
                .addGap(15, 15, 15)
                .addGroup(pnOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarSeleccionados)
                    .addComponent(jCheckBoxTodo))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnOpcionesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMostrarSeleccionados, btnNumProd, btnPrecioMedio});

        lblListaProd.setText("Lista de Productos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnProductosLayout = new javax.swing.GroupLayout(pnProductos);
        pnProductos.setLayout(pnProductosLayout);
        pnProductosLayout.setHorizontalGroup(
            pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProductosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProductosLayout.createSequentialGroup()
                        .addComponent(lblListaProd)
                        .addGap(0, 571, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        pnProductosLayout.setVerticalGroup(
            pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo)
                    .addComponent(pnOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDatosProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDatosProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResgistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResgistrarActionPerformed
        // TODO add your handling code here:

        // Validación de los campos
        if (txtCodProd.getText().trim().isEmpty() || !txtCodProd.getText().matches("\\d+")) {
            txtCodProd.setBorder(BorderFactory.createLineBorder(Color.red));
            txtCodProd.requestFocus();
            JOptionPane.showMessageDialog(this, "El código del producto debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtPrecio.getText().trim().isEmpty() || !txtPrecio.getText().matches("\\d+(\\.\\d{1,2})?")) {
            txtPrecio.setBorder(BorderFactory.createLineBorder(Color.red));
            txtPrecio.requestFocus();
            JOptionPane.showMessageDialog(this, "El precio debe ser un número decimal válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtProd.getText().trim().isEmpty()) {
            txtProd.setBorder(BorderFactory.createLineBorder(Color.red));
            txtProd.requestFocus();
            JOptionPane.showMessageDialog(this, "El nombre del producto es obligatorio.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Si pasa todas las validaciones, añadimos el producto
        Producto prd = new Producto();
        prd.setCodigoProd(Integer.parseInt(txtCodProd.getText()));
        prd.setPrecio(Float.parseFloat(txtPrecio.getText()));
        prd.setProducto(txtProd.getText());

        // Agregar al ArrayList
        arrayListProd.add(prd);

        // Añadir a la JTable
        Object[] lineaPer = {prd.getCodigoProd(), prd.getProducto(), prd.getPrecio(), false};
        modeloTabla.addRow(lineaPer);

        // Limpiar los campos
        txtCodProd.setText("");
        txtPrecio.setText("");
        txtProd.setText("");


    }//GEN-LAST:event_btnResgistrarActionPerformed

    private void btnPrecioMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecioMedioActionPerformed
        // TODO add your handling code here:

        double mediaPrecio = calcularMediaPrecio();
        JOptionPane.showMessageDialog(null, "El precio medio de los productos es: " + mediaPrecio);

    }//GEN-LAST:event_btnPrecioMedioActionPerformed

    private void btnNumProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumProdActionPerformed
        // TODO add your handling code here:

        int contador = arrayListProd.size();
        JOptionPane.showMessageDialog(null, "El número total de productos es: " + contador);

    }//GEN-LAST:event_btnNumProdActionPerformed

    private void btnMostrarSeleccionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSeleccionadosActionPerformed
        // TODO add your handling code here:

        String Reportes = "";
        JTextArea area = new JTextArea();
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            boolean sel = (boolean) jTable1.getValueAt(i, 3);
            if (sel) {
                Reportes += "Codigo : " + jTable1.getValueAt(i, 0) + " ; Producto : " + jTable1.getValueAt(i, 1) + "; Precio: " + jTable1.getValueAt(i, 2) + "\n";
            }
        }
        if ("".equals(Reportes)) {
            JOptionPane.showMessageDialog(null, "Antes de obtener los datos, debe de seleccionar por lo menos a un checkbox",
                    "Información", JOptionPane.WARNING_MESSAGE);
        } else {
            area.setText(Reportes);
            JOptionPane.showMessageDialog(this, area);
        }

    }//GEN-LAST:event_btnMostrarSeleccionadosActionPerformed

    private void jCheckBoxTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTodoActionPerformed
        // TODO add your handling code here:

        // Obtener el valor de la casilla de "Seleccionar Todos"
        boolean seleccionarTodos = jCheckBoxTodo.isSelected();

        // Iterar por todas las filas de la JTable
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            // Establecer el valor de la columna de selección (suponiendo que la columna "Acción" está en la cuarta posición)
            jTable1.setValueAt(seleccionarTodos, i, 3); // Cambiar el valor en la columna 3, que es donde está el checkbox
        }


    }//GEN-LAST:event_jCheckBoxTodoActionPerformed

    public double calcularMediaPrecio() {
        if (arrayListProd.isEmpty()) {
            return 0.0;
        }

        double sumaPrecio = 0.0;
        for (Producto prod : arrayListProd) {
            sumaPrecio += prod.getPrecio();
        }

        return Math.round(sumaPrecio / arrayListProd.size() * 100.0) / 100.0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarSeleccionados;
    private javax.swing.JButton btnNumProd;
    private javax.swing.JButton btnPrecioMedio;
    private javax.swing.JButton btnResgistrar;
    private javax.swing.JCheckBox jCheckBoxTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblDatosProd;
    private javax.swing.JLabel lblListaProd;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnDatosProd;
    private javax.swing.JPanel pnOpciones;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JPanel pnProductos;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProd;
    // End of variables declaration//GEN-END:variables
}
