
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pedro.rinpiz
 */
public class TresEnRaya extends javax.swing.JFrame {

    private boolean ganador = false;
    private static int contador = 0;
    private static int partX = 0;
    private static int partO = 0;
    private Color color;
    
    /**
     * Creates new form TresEnRaya
     */
    public TresEnRaya() {
        initComponents();
        setearTurno(contador);
        color = bt1_1.getBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bt1_1 = new javax.swing.JButton();
        bt1_2 = new javax.swing.JButton();
        bt1_3 = new javax.swing.JButton();
        bt2_1 = new javax.swing.JButton();
        bt2_2 = new javax.swing.JButton();
        bt2_3 = new javax.swing.JButton();
        bt3_1 = new javax.swing.JButton();
        bt3_2 = new javax.swing.JButton();
        bt3_3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTurno = new javax.swing.JLabel();
        lblPtsX = new javax.swing.JLabel();
        lblPtsO = new javax.swing.JLabel();
        btJugar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 255));

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        bt1_1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bt1_1.setForeground(new java.awt.Color(255, 153, 255));
        bt1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1_1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1_1);

        bt1_2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bt1_2.setForeground(new java.awt.Color(255, 153, 255));
        bt1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1_2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1_2);

        bt1_3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bt1_3.setForeground(new java.awt.Color(255, 153, 255));
        bt1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1_3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1_3);

        bt2_1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bt2_1.setForeground(new java.awt.Color(255, 153, 255));
        bt2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2_1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2_1);

        bt2_2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bt2_2.setForeground(new java.awt.Color(255, 153, 255));
        bt2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2_2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2_2);

        bt2_3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bt2_3.setForeground(new java.awt.Color(255, 153, 255));
        bt2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2_3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2_3);

        bt3_1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bt3_1.setForeground(new java.awt.Color(255, 153, 255));
        bt3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3_1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt3_1);

        bt3_2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bt3_2.setForeground(new java.awt.Color(255, 153, 255));
        bt3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3_2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt3_2);

        bt3_3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bt3_3.setForeground(new java.awt.Color(255, 153, 255));
        bt3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3_3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt3_3);

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));

        lblTurno.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTurno.setForeground(new java.awt.Color(0, 0, 0));
        lblTurno.setText("Turno de: ");

        lblPtsX.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblPtsX.setForeground(new java.awt.Color(0, 0, 204));
        lblPtsX.setText("X : 0");

        lblPtsO.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblPtsO.setForeground(new java.awt.Color(255, 51, 51));
        lblPtsO.setText("O : 0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPtsO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPtsX))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTurno)
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lblTurno)
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPtsX)
                    .addComponent(lblPtsO))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        btJugar.setForeground(new java.awt.Color(255, 153, 255));
        btJugar.setText("Jugar de nuevo");
        btJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJugarActionPerformed(evt);
            }
        });

        btSalir.setForeground(new java.awt.Color(255, 153, 255));
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btJugar)
                        .addGap(44, 44, 44)
                        .addComponent(btSalir)
                        .addGap(29, 29, 29)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btJugar)
                    .addComponent(btSalir))
                .addGap(39, 39, 39))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1_1ActionPerformed
        comprobarJugador(bt1_1);
    }//GEN-LAST:event_bt1_1ActionPerformed

    private void bt1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1_2ActionPerformed
        comprobarJugador(bt1_2);
    }//GEN-LAST:event_bt1_2ActionPerformed

    private void bt1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1_3ActionPerformed
        comprobarJugador(bt1_3);
    }//GEN-LAST:event_bt1_3ActionPerformed

    private void bt2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2_1ActionPerformed
        comprobarJugador(bt2_1);
    }//GEN-LAST:event_bt2_1ActionPerformed

    private void bt2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2_2ActionPerformed
        comprobarJugador(bt2_2);
    }//GEN-LAST:event_bt2_2ActionPerformed

    private void bt2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2_3ActionPerformed
        comprobarJugador(bt2_3);
    }//GEN-LAST:event_bt2_3ActionPerformed

    private void bt3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3_1ActionPerformed
        comprobarJugador(bt3_1);
    }//GEN-LAST:event_bt3_1ActionPerformed

    private void bt3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3_2ActionPerformed
        comprobarJugador(bt3_2);
    }//GEN-LAST:event_bt3_2ActionPerformed

    private void bt3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3_3ActionPerformed
        comprobarJugador(bt3_3);
    }//GEN-LAST:event_bt3_3ActionPerformed

    private void btJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJugarActionPerformed

        limpiarTablero();
    }//GEN-LAST:event_btJugarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TresEnRaya().setVisible(true);
            }
        });
    }
    
        private void comprobarJugador(JButton boton) throws HeadlessException {
        if (boton.getText().equalsIgnoreCase("")) {
            if (contador % 2 != 0) {
                boton.setText("X");
                comprobarGanador();
            } else {
                boton.setText("O");
                comprobarGanador();

            }
            contador++;
        } else 
        {
            JOptionPane.showMessageDialog(null, "Casilla ocupada!!");
        }
        

    }

    public void comprobarGanador() {

        
        if (contador >= 5 && contador <= 9) {
            JButton combianaciones[][]
                    = {
                        {bt1_1, bt1_2, bt1_3},
                        {bt2_1, bt2_2, bt2_3},
                        {bt3_1, bt3_2, bt3_3},
                        {bt1_1, bt2_1, bt3_1},
                        {bt1_2, bt2_2, bt3_2},
                        {bt1_3, bt2_3, bt3_3},
                        {bt1_1, bt2_2, bt3_3},
                        {bt1_3, bt2_2, bt3_1},};
            for (int cont = 0; cont < combianaciones.length; cont++) {
                if (combianaciones[cont][0].getText().equals("X") && combianaciones[cont][1].getText().equals("X") && combianaciones[cont][2].getText().equals("X")) {
                    combianaciones[cont][0].setBackground(Color.green);
                    combianaciones[cont][1].setBackground(Color.green);
                    combianaciones[cont][2].setBackground(Color.green);
                    JOptionPane.showMessageDialog(null, "Has Ganado Jugador X!!");
                    limpiarTablero();
                    lblPtsX.setText("X : " + ++partX);
                    ganador = true;
                } 
                else if (combianaciones[cont][0].getText().equals("O") && combianaciones[cont][1].getText().equals("O") && combianaciones[cont][2].getText().equals("O")) {
                    combianaciones[cont][0].setBackground(Color.red);
                    combianaciones[cont][1].setBackground(Color.red);
                    combianaciones[cont][2].setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Has Ganado Jugador O!!");
                    limpiarTablero();
                    lblPtsO.setText("O : " + ++partO);
                    ganador = true;
                }
                
            }
        }
        if(contador == 9 && ganador == false)
        {
            JOptionPane.showMessageDialog(null, "Empate");
            limpiarTablero(); 
        }
        ganador = false;
    }

    private void limpiarTablero() {
        setearTurno(contador);
        contador = 0;
        JButton combianaciones[][]
                = {
                    {bt1_1, bt1_2, bt1_3},
                    {bt2_1, bt2_2, bt2_3},
                    {bt3_1, bt3_2, bt3_3},
                    {bt1_1, bt2_1, bt3_1},
                    {bt1_2, bt2_2, bt3_2},
                    {bt1_3, bt2_3, bt3_3},
                    {bt1_1, bt2_2, bt3_3},
                    {bt1_3, bt2_2, bt3_1},};
        for (int i = 0; i < combianaciones.length; i++) {
            for (int e = 0; e < combianaciones[i].length; e++) {
                combianaciones[i][e].setText("");
                combianaciones[i][e].setBackground(color);
            }
        }
    }

    private void setearTurno(int contador) {
        if (contador % 2 != 0) {
            lblTurno.setText("Turno de X");
        } else {
            lblTurno.setText("Turno de O");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1_1;
    private javax.swing.JButton bt1_2;
    private javax.swing.JButton bt1_3;
    private javax.swing.JButton bt2_1;
    private javax.swing.JButton bt2_2;
    private javax.swing.JButton bt2_3;
    private javax.swing.JButton bt3_1;
    private javax.swing.JButton bt3_2;
    private javax.swing.JButton bt3_3;
    private javax.swing.JButton btJugar;
    private javax.swing.JButton btSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblPtsO;
    private javax.swing.JLabel lblPtsX;
    private javax.swing.JLabel lblTurno;
    // End of variables declaration//GEN-END:variables
}
