/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package semanaDeportiva;

import java.awt.Color;

/**
 *
 * @author unai.esggir
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipial
     */
    public FrmPrincipal() {
        initComponents();
        pnPrincipal.setBackground(new Color(204,255,255));
        pnLunes.setBackground(new Color(102,102,255));
        pnMartes.setBackground(new Color(255,204,204));
        pnMiercoles.setBackground(new Color(255,255,102));
        pnJueves.setBackground(new Color(0,255,0));
        pnViernes.setBackground(new Color(0,204,204));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCabecera = new javax.swing.JPanel();
        btnLunes = new javax.swing.JButton();
        btnMartes = new javax.swing.JButton();
        btnMiercoles = new javax.swing.JButton();
        btnJueves = new javax.swing.JButton();
        btnViernes = new javax.swing.JButton();
        lblDiaHora = new javax.swing.JLabel();
        pnCuerpo = new javax.swing.JPanel();
        pnPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLugar = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        pnLunes = new javax.swing.JPanel();
        lblFechaL = new javax.swing.JLabel();
        lblAperturaL = new javax.swing.JLabel();
        lblHorarioL = new javax.swing.JLabel();
        lblEventoL = new javax.swing.JLabel();
        pnMartes = new javax.swing.JPanel();
        lblFechaM = new javax.swing.JLabel();
        lblAperturaM = new javax.swing.JLabel();
        lblHorarioM = new javax.swing.JLabel();
        lblEventoM = new javax.swing.JLabel();
        pnMiercoles = new javax.swing.JPanel();
        lblFechaX = new javax.swing.JLabel();
        lblAperturaX = new javax.swing.JLabel();
        lblHorarioX = new javax.swing.JLabel();
        lblEventoX = new javax.swing.JLabel();
        pnJueves = new javax.swing.JPanel();
        lblFechaJ = new javax.swing.JLabel();
        lblAperturaJ = new javax.swing.JLabel();
        lblHorarioJ = new javax.swing.JLabel();
        lblEventoJ = new javax.swing.JLabel();
        pnViernes = new javax.swing.JPanel();
        lblFechaV = new javax.swing.JLabel();
        lblAperturaV = new javax.swing.JLabel();
        lblHorarioV = new javax.swing.JLabel();
        lblEventoV = new javax.swing.JLabel();
        pnPie = new javax.swing.JPanel();
        lblInformacion = new javax.swing.JLabel();
        btnRestaurar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnCabecera.setBackground(new java.awt.Color(204, 204, 204));
        pnCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnLunes.setText("LUNES");
        btnLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLunesActionPerformed(evt);
            }
        });

        btnMartes.setText("MARTES");
        btnMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMartesActionPerformed(evt);
            }
        });

        btnMiercoles.setText("MIERCOLES");
        btnMiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiercolesActionPerformed(evt);
            }
        });

        btnJueves.setText("JUEVES");
        btnJueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuevesActionPerformed(evt);
            }
        });

        btnViernes.setText("VIERNES");
        btnViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViernesActionPerformed(evt);
            }
        });

        lblDiaHora.setText("DIA Y HORA DEL ACONTECIMIENTO");

        javax.swing.GroupLayout pnCabeceraLayout = new javax.swing.GroupLayout(pnCabecera);
        pnCabecera.setLayout(pnCabeceraLayout);
        pnCabeceraLayout.setHorizontalGroup(
            pnCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCabeceraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnCabeceraLayout.createSequentialGroup()
                        .addComponent(btnLunes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMartes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMiercoles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJueves)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViernes)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnCabeceraLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnJueves, btnLunes, btnMartes, btnMiercoles, btnViernes});

        pnCabeceraLayout.setVerticalGroup(
            pnCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCabeceraLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLunes)
                    .addComponent(btnMartes)
                    .addComponent(btnMiercoles)
                    .addComponent(btnJueves)
                    .addComponent(btnViernes))
                .addGap(42, 42, 42)
                .addComponent(lblDiaHora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnCuerpo.setBackground(new java.awt.Color(204, 255, 255));
        pnCuerpo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnCuerpo.setLayout(new java.awt.CardLayout());

        pnPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        pnPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitulo.setText("SEMANA DEPORTIVA EN EL PALACIO DE FESTIVALES DE SANTANDER (de Lunes a Viernes)");

        lblLugar.setText("Lugar: Auditorium");

        lblFecha.setText("Fechas: del Lunes 9 al Viernes 13 de Diciembre");

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/semana.png"))); // NOI18N

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen)
                    .addComponent(lblTitulo)
                    .addComponent(lblLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(244, 244, 244))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblLugar)
                .addGap(18, 18, 18)
                .addComponent(lblFecha)
                .addGap(52, 52, 52)
                .addComponent(lblImagen)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnPrincipal, "card2");

        pnLunes.setBackground(new java.awt.Color(102, 102, 255));

        lblFechaL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaL.setText("Dia 9/12 Lunes:");

        lblAperturaL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAperturaL.setText("Apertura de las puertas a las 9:00 horas");

        lblHorarioL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHorarioL.setText("Horario(s) evento 9-14h y de 16-21h");

        lblEventoL.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblEventoL.setText("INAUGURACION, INTRODUCCION A TODOS");

        javax.swing.GroupLayout pnLunesLayout = new javax.swing.GroupLayout(pnLunes);
        pnLunes.setLayout(pnLunesLayout);
        pnLunesLayout.setHorizontalGroup(
            pnLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLunesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLunesLayout.createSequentialGroup()
                        .addComponent(lblHorarioL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnLunesLayout.createSequentialGroup()
                        .addGroup(pnLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnLunesLayout.createSequentialGroup()
                                .addComponent(lblFechaL)
                                .addGap(273, 273, 273)
                                .addComponent(lblAperturaL))
                            .addComponent(lblEventoL))
                        .addGap(0, 179, Short.MAX_VALUE))))
        );
        pnLunesLayout.setVerticalGroup(
            pnLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLunesLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaL)
                    .addComponent(lblAperturaL))
                .addGap(47, 47, 47)
                .addComponent(lblHorarioL)
                .addGap(126, 126, 126)
                .addComponent(lblEventoL)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnLunes, "card3");

        pnMartes.setBackground(new java.awt.Color(255, 204, 204));

        lblFechaM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaM.setText("Dia 10/12 Martes:");

        lblAperturaM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAperturaM.setText("Apertura de las puertas a las 9:00 horas");

        lblHorarioM.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHorarioM.setText("Horario(s) evento 9-14h y de 16-21h");

        lblEventoM.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblEventoM.setText("DIA DEL FUTBOL");

        javax.swing.GroupLayout pnMartesLayout = new javax.swing.GroupLayout(pnMartes);
        pnMartes.setLayout(pnMartesLayout);
        pnMartesLayout.setHorizontalGroup(
            pnMartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMartesLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnMartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMartesLayout.createSequentialGroup()
                        .addComponent(lblEventoM)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnMartesLayout.createSequentialGroup()
                        .addComponent(lblHorarioM)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnMartesLayout.createSequentialGroup()
                        .addComponent(lblFechaM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                        .addComponent(lblAperturaM)
                        .addGap(146, 146, 146))))
        );
        pnMartesLayout.setVerticalGroup(
            pnMartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMartesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnMartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaM)
                    .addComponent(lblAperturaM))
                .addGap(37, 37, 37)
                .addComponent(lblHorarioM)
                .addGap(102, 102, 102)
                .addComponent(lblEventoM)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnMartes, "card4");

        pnMiercoles.setBackground(new java.awt.Color(255, 255, 102));

        lblFechaX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaX.setText("Dia 11/12 Miercoles:");

        lblAperturaX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAperturaX.setText("Apertura de las puertas a las 9:00 horas");

        lblHorarioX.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHorarioX.setText("Horario(s) evento 9-14h y de 16-21h");

        lblEventoX.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblEventoX.setText("DIA DEL BALONCESTO");

        javax.swing.GroupLayout pnMiercolesLayout = new javax.swing.GroupLayout(pnMiercoles);
        pnMiercoles.setLayout(pnMiercolesLayout);
        pnMiercolesLayout.setHorizontalGroup(
            pnMiercolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMiercolesLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnMiercolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMiercolesLayout.createSequentialGroup()
                        .addComponent(lblFechaX)
                        .addGap(254, 254, 254)
                        .addComponent(lblAperturaX))
                    .addComponent(lblHorarioX)
                    .addComponent(lblEventoX))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        pnMiercolesLayout.setVerticalGroup(
            pnMiercolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMiercolesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnMiercolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaX)
                    .addComponent(lblAperturaX))
                .addGap(49, 49, 49)
                .addComponent(lblHorarioX)
                .addGap(98, 98, 98)
                .addComponent(lblEventoX)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnMiercoles, "card5");

        pnJueves.setBackground(new java.awt.Color(0, 255, 0));

        lblFechaJ.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaJ.setText("Dia 12/12 Jueves:");

        lblAperturaJ.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAperturaJ.setText("Apertura de las puertas a las 9:00 horas");

        lblHorarioJ.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHorarioJ.setText("Horario(s) evento 9-14h y de 16-21h");

        lblEventoJ.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblEventoJ.setText("DIA DEL CICLISMO");

        javax.swing.GroupLayout pnJuevesLayout = new javax.swing.GroupLayout(pnJueves);
        pnJueves.setLayout(pnJuevesLayout);
        pnJuevesLayout.setHorizontalGroup(
            pnJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnJuevesLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(pnJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnJuevesLayout.createSequentialGroup()
                        .addGroup(pnJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEventoJ)
                            .addComponent(lblHorarioJ))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnJuevesLayout.createSequentialGroup()
                        .addComponent(lblFechaJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addComponent(lblAperturaJ)
                        .addGap(144, 144, 144))))
        );
        pnJuevesLayout.setVerticalGroup(
            pnJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnJuevesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaJ)
                    .addComponent(lblAperturaJ))
                .addGap(39, 39, 39)
                .addComponent(lblHorarioJ)
                .addGap(95, 95, 95)
                .addComponent(lblEventoJ)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnJueves, "card6");

        pnViernes.setBackground(new java.awt.Color(0, 204, 204));

        lblFechaV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaV.setText("Dia 13/12 Viernes:");

        lblAperturaV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAperturaV.setText("Apertura de las puertas a las 9:00 horas");

        lblHorarioV.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHorarioV.setText("Horario(s) evento 9-18h");

        lblEventoV.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblEventoV.setText("FIESTA DE CLAUSURA A ULTIMA HORA");

        javax.swing.GroupLayout pnViernesLayout = new javax.swing.GroupLayout(pnViernes);
        pnViernes.setLayout(pnViernesLayout);
        pnViernesLayout.setHorizontalGroup(
            pnViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnViernesLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(pnViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEventoV)
                    .addGroup(pnViernesLayout.createSequentialGroup()
                        .addGroup(pnViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorarioV)
                            .addComponent(lblFechaV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAperturaV)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        pnViernesLayout.setVerticalGroup(
            pnViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnViernesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaV)
                    .addComponent(lblAperturaV))
                .addGap(37, 37, 37)
                .addComponent(lblHorarioV)
                .addGap(89, 89, 89)
                .addComponent(lblEventoV)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnViernes, "card7");

        pnPie.setBackground(new java.awt.Color(204, 204, 204));
        pnPie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblInformacion.setText("Pulsa sobre los botones para ver la información del Festival");

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPieLayout = new javax.swing.GroupLayout(pnPie);
        pnPie.setLayout(pnPieLayout);
        pnPieLayout.setHorizontalGroup(
            pnPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPieLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPieLayout.createSequentialGroup()
                        .addComponent(lblInformacion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnPieLayout.createSequentialGroup()
                        .addComponent(btnRestaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(28, 28, 28))))
        );

        pnPieLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRestaurar, btnSalir});

        pnPieLayout.setVerticalGroup(
            pnPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPieLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblInformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestaurar)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(pnPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        // TODO add your handling code here:
        lblDiaHora.setText("DIA Y HORA DEL ACONTECIMIENTO");
        pnPrincipal.setVisible(true);
        pnLunes.setVisible(false);
        pnMartes.setVisible(false);
        pnMiercoles.setVisible(false);
        pnJueves.setVisible(false);
        pnViernes.setVisible(false);
        
        btnRestaurar.setEnabled(false);
        btnLunes.setEnabled(true);
        btnMartes.setEnabled(true);
        btnMiercoles.setEnabled(true);
        btnJueves.setEnabled(true);
        btnViernes.setEnabled(true);
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLunesActionPerformed
        // TODO add your handling code here:
        lblDiaHora.setText("Lunes 09/12 Horarios 9:00-14:00 y de 16:00 a 21:00");
        pnPrincipal.setVisible(false);
        pnLunes.setVisible(true);
        pnMartes.setVisible(false);
        pnMiercoles.setVisible(false);
        pnJueves.setVisible(false);
        pnViernes.setVisible(false);
        
        btnRestaurar.setEnabled(true);
        btnLunes.setEnabled(false);
        btnMartes.setEnabled(true);
        btnMiercoles.setEnabled(true);
        btnJueves.setEnabled(true);
        btnViernes.setEnabled(true);
    }//GEN-LAST:event_btnLunesActionPerformed

    private void btnMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMartesActionPerformed
        // TODO add your handling code here:
        lblDiaHora.setText("Martes 10/12 Horarios 9:00-14:00 y de 16:00 a 21:00");
        pnPrincipal.setVisible(false);
        pnLunes.setVisible(false);
        pnMartes.setVisible(true);
        pnMiercoles.setVisible(false);
        pnJueves.setVisible(false);
        pnViernes.setVisible(false);
        
        btnRestaurar.setEnabled(true);
        btnLunes.setEnabled(true);
        btnMartes.setEnabled(false);
        btnMiercoles.setEnabled(true);
        btnJueves.setEnabled(true);
        btnViernes.setEnabled(true);
    }//GEN-LAST:event_btnMartesActionPerformed

    private void btnMiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiercolesActionPerformed
        // TODO add your handling code here:
        lblDiaHora.setText("Miercoles 11/12 Horarios 9:00-14:00 y de 16:00 a 21:00");
        pnPrincipal.setVisible(false);
        pnLunes.setVisible(false);
        pnMartes.setVisible(false);
        pnMiercoles.setVisible(true);
        pnJueves.setVisible(false);
        pnViernes.setVisible(false);
        
        btnRestaurar.setEnabled(true);
        btnLunes.setEnabled(true);
        btnMartes.setEnabled(true);
        btnMiercoles.setEnabled(false);
        btnJueves.setEnabled(true);
        btnViernes.setEnabled(true);
    }//GEN-LAST:event_btnMiercolesActionPerformed

    private void btnJuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuevesActionPerformed
        // TODO add your handling code here:
        lblDiaHora.setText("Jueves 12/12 Horarios de 9:00-14:00 y de 16:00 a 21:00");
        pnPrincipal.setVisible(false);
        pnLunes.setVisible(false);
        pnMartes.setVisible(false);
        pnMiercoles.setVisible(false);
        pnJueves.setVisible(true);
        pnViernes.setVisible(false);
        
        btnRestaurar.setEnabled(true);
        btnLunes.setEnabled(true);
        btnMartes.setEnabled(true);
        btnMiercoles.setEnabled(true);
        btnJueves.setEnabled(false);
        btnViernes.setEnabled(true);
    }//GEN-LAST:event_btnJuevesActionPerformed

    private void btnViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViernesActionPerformed
        // TODO add your handling code here:
        lblDiaHora.setText("Viernes 13/12 Horarios de 9:00 a 18:00");
        pnPrincipal.setVisible(false);
        pnLunes.setVisible(false);
        pnMartes.setVisible(false);
        pnMiercoles.setVisible(false);
        pnJueves.setVisible(false);
        pnViernes.setVisible(true);
        
        btnRestaurar.setEnabled(true);
        btnLunes.setEnabled(true);
        btnMartes.setEnabled(true);
        btnMiercoles.setEnabled(true);
        btnJueves.setEnabled(true);
        btnViernes.setEnabled(false);
    }//GEN-LAST:event_btnViernesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJueves;
    private javax.swing.JButton btnLunes;
    private javax.swing.JButton btnMartes;
    private javax.swing.JButton btnMiercoles;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnViernes;
    private javax.swing.JLabel lblAperturaJ;
    private javax.swing.JLabel lblAperturaL;
    private javax.swing.JLabel lblAperturaM;
    private javax.swing.JLabel lblAperturaV;
    private javax.swing.JLabel lblAperturaX;
    private javax.swing.JLabel lblDiaHora;
    private javax.swing.JLabel lblEventoJ;
    private javax.swing.JLabel lblEventoL;
    private javax.swing.JLabel lblEventoM;
    private javax.swing.JLabel lblEventoV;
    private javax.swing.JLabel lblEventoX;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaJ;
    private javax.swing.JLabel lblFechaL;
    private javax.swing.JLabel lblFechaM;
    private javax.swing.JLabel lblFechaV;
    private javax.swing.JLabel lblFechaX;
    private javax.swing.JLabel lblHorarioJ;
    private javax.swing.JLabel lblHorarioL;
    private javax.swing.JLabel lblHorarioM;
    private javax.swing.JLabel lblHorarioV;
    private javax.swing.JLabel lblHorarioX;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnCabecera;
    private javax.swing.JPanel pnCuerpo;
    private javax.swing.JPanel pnJueves;
    private javax.swing.JPanel pnLunes;
    private javax.swing.JPanel pnMartes;
    private javax.swing.JPanel pnMiercoles;
    private javax.swing.JPanel pnPie;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JPanel pnViernes;
    // End of variables declaration//GEN-END:variables
}
