/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio1;

/**
 *
 * @author adrian.veldie.2
 */
public class Paneles extends javax.swing.JFrame {

    /**
     * Creates new form Paneles
     */
    public Paneles() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Semana Deportiva");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCabecera = new javax.swing.JPanel();
        btnLunes = new javax.swing.JButton();
        btnMartes = new javax.swing.JButton();
        btnMiercoles = new javax.swing.JButton();
        btnJueves = new javax.swing.JButton();
        btnViernes = new javax.swing.JButton();
        lblCabecera = new javax.swing.JLabel();
        pnCuerpo = new javax.swing.JPanel();
        pnPortada = new javax.swing.JPanel();
        lblInfoPortada = new javax.swing.JLabel();
        lblLugarPortada = new javax.swing.JLabel();
        lblFechaPortada = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        pnViernes = new javax.swing.JPanel();
        lblDiaViernes = new javax.swing.JLabel();
        lblHorarioViernes = new javax.swing.JLabel();
        lblFiestaViernes = new javax.swing.JLabel();
        pnJueves = new javax.swing.JPanel();
        lblDiaJueves = new javax.swing.JLabel();
        lblHorarioJueves = new javax.swing.JLabel();
        lblCiclismoJueves = new javax.swing.JLabel();
        pnMiercoles = new javax.swing.JPanel();
        lblDiaMiercoles = new javax.swing.JLabel();
        lblHorarioMiercoles = new javax.swing.JLabel();
        lblBaloncestoMiercoles = new javax.swing.JLabel();
        pnLunes = new javax.swing.JPanel();
        lblDiaLunes = new javax.swing.JLabel();
        lblHorarioLunes = new javax.swing.JLabel();
        lblInaugusarioLunes = new javax.swing.JLabel();
        pnMartes = new javax.swing.JPanel();
        lblDiaMartes = new javax.swing.JLabel();
        lblHorarioMartes = new javax.swing.JLabel();
        lblFutbolMartes = new javax.swing.JLabel();
        pnPiePagina = new javax.swing.JPanel();
        lblBotones = new javax.swing.JLabel();
        btnRestaurar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLunes.setText("LUNES");
        btnLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLunesActionPerformed(evt);
            }
        });

        btnMartes.setText("MARTES");
        btnMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMartesActionPerformed(evt);
            }
        });

        btnMiercoles.setText("MIERCOLES");
        btnMiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiercolesActionPerformed(evt);
            }
        });

        btnJueves.setText("JUEVES");
        btnJueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuevesActionPerformed(evt);
            }
        });

        btnViernes.setText("VIERNES");
        btnViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViernesActionPerformed(evt);
            }
        });

        lblCabecera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCabecera.setText("DIA Y HORA DEL ACONTECIMIENTO");

        javax.swing.GroupLayout pnCabeceraLayout = new javax.swing.GroupLayout(pnCabecera);
        pnCabecera.setLayout(pnCabeceraLayout);
        pnCabeceraLayout.setHorizontalGroup(
            pnCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCabeceraLayout.createSequentialGroup()
                        .addComponent(btnLunes)
                        .addGap(18, 18, 18)
                        .addComponent(btnMartes)
                        .addGap(28, 28, 28)
                        .addComponent(btnMiercoles)
                        .addGap(18, 18, 18)
                        .addComponent(btnJueves)
                        .addGap(18, 18, 18)
                        .addComponent(btnViernes))
                    .addComponent(lblCabecera))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnCabeceraLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnJueves, btnLunes, btnMartes, btnMiercoles, btnViernes});

        pnCabeceraLayout.setVerticalGroup(
            pnCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCabeceraLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLunes)
                    .addComponent(btnMartes)
                    .addComponent(btnMiercoles)
                    .addComponent(btnJueves)
                    .addComponent(btnViernes))
                .addGap(18, 18, 18)
                .addComponent(lblCabecera)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnCabeceraLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnJueves, btnLunes, btnMartes, btnMiercoles, btnViernes});

        pnCuerpo.setBackground(new java.awt.Color(153, 204, 255));
        pnCuerpo.setLayout(new java.awt.CardLayout());

        pnPortada.setBackground(new java.awt.Color(153, 204, 255));

        lblInfoPortada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInfoPortada.setText("SEMANA DEPORTIVA EN EL PALACIO DE FESTIVALES DE SANTANDER (de Lunes a Viernes)");

        lblLugarPortada.setText("Lugar: Auditorium");

        lblFechaPortada.setText("Fechas: del Lunes 9 al Viernes 13 de Diciembre");

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/semana.png"))); // NOI18N
        lblImg.setText("IMAGEN");

        javax.swing.GroupLayout pnPortadaLayout = new javax.swing.GroupLayout(pnPortada);
        pnPortada.setLayout(pnPortadaLayout);
        pnPortadaLayout.setHorizontalGroup(
            pnPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPortadaLayout.createSequentialGroup()
                .addGroup(pnPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPortadaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaPortada)
                            .addComponent(lblLugarPortada)
                            .addComponent(lblInfoPortada)))
                    .addGroup(pnPortadaLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblImg)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        pnPortadaLayout.setVerticalGroup(
            pnPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPortadaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblInfoPortada)
                .addGap(18, 18, 18)
                .addComponent(lblLugarPortada)
                .addGap(18, 18, 18)
                .addComponent(lblFechaPortada)
                .addGap(88, 88, 88)
                .addComponent(lblImg)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnPortada, "card6");

        pnViernes.setBackground(new java.awt.Color(255, 204, 153));

        lblDiaViernes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiaViernes.setText("Dia 13/12 Viernes:            Apertura de las Puertas a las 9:00 horas");

        lblHorarioViernes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHorarioViernes.setText("Horario(s) evento 9-18 h");

        lblFiestaViernes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFiestaViernes.setText("FIESTA DE CLAUSURA A ULTIMA HORA");

        javax.swing.GroupLayout pnViernesLayout = new javax.swing.GroupLayout(pnViernes);
        pnViernes.setLayout(pnViernesLayout);
        pnViernesLayout.setHorizontalGroup(
            pnViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnViernesLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(pnViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFiestaViernes)
                    .addComponent(lblHorarioViernes)
                    .addComponent(lblDiaViernes))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        pnViernesLayout.setVerticalGroup(
            pnViernesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnViernesLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblDiaViernes)
                .addGap(67, 67, 67)
                .addComponent(lblHorarioViernes)
                .addGap(89, 89, 89)
                .addComponent(lblFiestaViernes)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnViernes, "card7");

        pnJueves.setBackground(new java.awt.Color(255, 204, 255));

        lblDiaJueves.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiaJueves.setText("Dia 12/12 Jueves:             Apertura de las puertas a las 9:00 horas");

        lblHorarioJueves.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHorarioJueves.setText("Horario(s) evento 9-14h y de 16-21h ");

        lblCiclismoJueves.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCiclismoJueves.setText("DIA DE CICLISMO");

        javax.swing.GroupLayout pnJuevesLayout = new javax.swing.GroupLayout(pnJueves);
        pnJueves.setLayout(pnJuevesLayout);
        pnJuevesLayout.setHorizontalGroup(
            pnJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnJuevesLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(pnJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiaJueves)
                    .addComponent(lblCiclismoJueves)
                    .addComponent(lblHorarioJueves))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        pnJuevesLayout.setVerticalGroup(
            pnJuevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnJuevesLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblDiaJueves)
                .addGap(64, 64, 64)
                .addComponent(lblHorarioJueves)
                .addGap(74, 74, 74)
                .addComponent(lblCiclismoJueves)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnJueves, "card6");

        pnMiercoles.setBackground(new java.awt.Color(0, 255, 204));

        lblDiaMiercoles.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiaMiercoles.setText("Dia 11/12 Miercoles:      Apertura de las puertas a las 9:00 horas");

        lblHorarioMiercoles.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHorarioMiercoles.setText("Horario(s) evento 9-14h y de 16-21h");

        lblBaloncestoMiercoles.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBaloncestoMiercoles.setText("DIA DEL BALONCESTO");

        javax.swing.GroupLayout pnMiercolesLayout = new javax.swing.GroupLayout(pnMiercoles);
        pnMiercoles.setLayout(pnMiercolesLayout);
        pnMiercolesLayout.setHorizontalGroup(
            pnMiercolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMiercolesLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnMiercolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBaloncestoMiercoles)
                    .addComponent(lblHorarioMiercoles)
                    .addComponent(lblDiaMiercoles))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        pnMiercolesLayout.setVerticalGroup(
            pnMiercolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMiercolesLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblDiaMiercoles)
                .addGap(75, 75, 75)
                .addComponent(lblHorarioMiercoles)
                .addGap(94, 94, 94)
                .addComponent(lblBaloncestoMiercoles)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnMiercoles, "card5");

        pnLunes.setBackground(new java.awt.Color(255, 255, 153));

        lblDiaLunes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiaLunes.setText("Dia 09/12 Lunes:                    Apertura de las puertas a las 9:00 horas");

        lblHorarioLunes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHorarioLunes.setText("Horario(s) evento 9-14h y de 16-21h");

        lblInaugusarioLunes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblInaugusarioLunes.setText("INAUGURACION, INTRODUCCION A TODOS");

        javax.swing.GroupLayout pnLunesLayout = new javax.swing.GroupLayout(pnLunes);
        pnLunes.setLayout(pnLunesLayout);
        pnLunesLayout.setHorizontalGroup(
            pnLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLunesLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInaugusarioLunes)
                    .addComponent(lblHorarioLunes)
                    .addComponent(lblDiaLunes))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        pnLunesLayout.setVerticalGroup(
            pnLunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLunesLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblDiaLunes)
                .addGap(74, 74, 74)
                .addComponent(lblHorarioLunes)
                .addGap(90, 90, 90)
                .addComponent(lblInaugusarioLunes)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnLunes, "card3");

        pnMartes.setBackground(new java.awt.Color(255, 204, 204));

        lblDiaMartes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiaMartes.setText("Dia 10/12 Martes:        Apertura de las puertas a las 9:00 horas");

        lblHorarioMartes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHorarioMartes.setText("Horario(s) evento 9-14h y de 16-21h");

        lblFutbolMartes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFutbolMartes.setText("DIA DE FUTBOL");

        javax.swing.GroupLayout pnMartesLayout = new javax.swing.GroupLayout(pnMartes);
        pnMartes.setLayout(pnMartesLayout);
        pnMartesLayout.setHorizontalGroup(
            pnMartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMartesLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(pnMartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFutbolMartes)
                    .addComponent(lblHorarioMartes)
                    .addComponent(lblDiaMartes))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        pnMartesLayout.setVerticalGroup(
            pnMartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMartesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblDiaMartes)
                .addGap(75, 75, 75)
                .addComponent(lblHorarioMartes)
                .addGap(77, 77, 77)
                .addComponent(lblFutbolMartes)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        pnCuerpo.add(pnMartes, "card4");

        lblBotones.setText("Pulsa sobre los botones para ver la informacion del Festival");

        btnRestaurar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPiePaginaLayout = new javax.swing.GroupLayout(pnPiePagina);
        pnPiePagina.setLayout(pnPiePaginaLayout);
        pnPiePaginaLayout.setHorizontalGroup(
            pnPiePaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPiePaginaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnPiePaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPiePaginaLayout.createSequentialGroup()
                        .addComponent(lblBotones)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnPiePaginaLayout.createSequentialGroup()
                        .addComponent(btnRestaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(57, 57, 57))))
        );

        pnPiePaginaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRestaurar, btnSalir});

        pnPiePaginaLayout.setVerticalGroup(
            pnPiePaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPiePaginaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblBotones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(pnPiePaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestaurar)
                    .addComponent(btnSalir))
                .addGap(15, 15, 15))
        );

        pnPiePaginaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRestaurar, btnSalir});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnPiePagina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnPiePagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLunesActionPerformed
        // TODO add your handling code here:
        
        pnLunes.setVisible(true);
        pnMartes.setVisible(false);
        pnMiercoles.setVisible(false);
        pnJueves.setVisible(false);
        pnViernes.setVisible(false);
        pnPortada.setVisible(false);
        
        btnLunes.setEnabled(false);
        btnMartes.setEnabled(true);
        btnMiercoles.setEnabled(true);
        btnJueves.setEnabled(true);
        btnViernes.setEnabled(true);
        
        lblCabecera.setText("Lunes 09/12 Horarios 9:00-14:00 y de 16:00 a 21:00");
        
    }//GEN-LAST:event_btnLunesActionPerformed

    private void btnMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMartesActionPerformed
        // TODO add your handling code here:
        pnLunes.setVisible(false);
        pnMartes.setVisible(true);
        pnMiercoles.setVisible(false);
        pnJueves.setVisible(false);
        pnViernes.setVisible(false);
        pnPortada.setVisible(false);
        
        btnLunes.setEnabled(true);
        btnMartes.setEnabled(false);
        btnMiercoles.setEnabled(true);
        btnJueves.setEnabled(true);
        btnViernes.setEnabled(true);
        
        lblCabecera.setText("Martes 10/12 Horarios 9:00-14:00 y de 16:00 a 21:00");
    }//GEN-LAST:event_btnMartesActionPerformed

    private void btnMiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiercolesActionPerformed
        // TODO add your handling code here:
        
        pnLunes.setVisible(false);
        pnMartes.setVisible(false);
        pnMiercoles.setVisible(true);
        pnJueves.setVisible(false);
        pnViernes.setVisible(false);
        pnPortada.setVisible(false);
        
        btnLunes.setEnabled(true);
        btnMartes.setEnabled(true);
        btnMiercoles.setEnabled(false);
        btnJueves.setEnabled(true);
        btnViernes.setEnabled(true);
        
        lblCabecera.setText("Miercoles 11/12 Horarios 9:00-14:00 y de 16:00 a 21:00");
        
    }//GEN-LAST:event_btnMiercolesActionPerformed

    private void btnJuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuevesActionPerformed
        // TODO add your handling code here:
        pnLunes.setVisible(false);
        pnMartes.setVisible(false);
        pnMiercoles.setVisible(false);
        pnJueves.setVisible(true);
        pnViernes.setVisible(false);
        pnPortada.setVisible(false);
        
        btnLunes.setEnabled(true);
        btnMartes.setEnabled(true);
        btnMiercoles.setEnabled(true);
        btnJueves.setEnabled(false);
        btnViernes.setEnabled(true);
        
        lblCabecera.setText("Jueves 12/12 Horarios 9:00-14:00 y de 16:00 a 21:00");
    }//GEN-LAST:event_btnJuevesActionPerformed

    private void btnViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViernesActionPerformed
        // TODO add your handling code here:
        
        pnLunes.setVisible(false);
        pnMartes.setVisible(false);
        pnMiercoles.setVisible(false);
        pnJueves.setVisible(false);
        pnViernes.setVisible(true);
        pnPortada.setVisible(false);
        
        btnLunes.setEnabled(true);
        btnMartes.setEnabled(true);
        btnMiercoles.setEnabled(true);
        btnJueves.setEnabled(true);
        btnViernes.setEnabled(false);
        
        lblCabecera.setText("Viernes 13/12 Horarios 9:00-14:00 y de 16:00 a 21:00");
        
    }//GEN-LAST:event_btnViernesActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        // TODO add your handling code here:
        
        pnLunes.setVisible(false);
        pnMartes.setVisible(false);
        pnMiercoles.setVisible(false);
        pnJueves.setVisible(false);
        pnViernes.setVisible(false);
        pnPortada.setVisible(true);
        
        btnLunes.setEnabled(true);
        btnMartes.setEnabled(true);
        btnMiercoles.setEnabled(true);
        btnJueves.setEnabled(true);
        btnViernes.setEnabled(true);
        
        lblCabecera.setText("DIA Y HORA DEL ACONTECIMIENTO");
        
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paneles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJueves;
    private javax.swing.JButton btnLunes;
    private javax.swing.JButton btnMartes;
    private javax.swing.JButton btnMiercoles;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnViernes;
    private javax.swing.JLabel lblBaloncestoMiercoles;
    private javax.swing.JLabel lblBotones;
    private javax.swing.JLabel lblCabecera;
    private javax.swing.JLabel lblCiclismoJueves;
    private javax.swing.JLabel lblDiaJueves;
    private javax.swing.JLabel lblDiaLunes;
    private javax.swing.JLabel lblDiaMartes;
    private javax.swing.JLabel lblDiaMiercoles;
    private javax.swing.JLabel lblDiaViernes;
    private javax.swing.JLabel lblFechaPortada;
    private javax.swing.JLabel lblFiestaViernes;
    private javax.swing.JLabel lblFutbolMartes;
    private javax.swing.JLabel lblHorarioJueves;
    private javax.swing.JLabel lblHorarioLunes;
    private javax.swing.JLabel lblHorarioMartes;
    private javax.swing.JLabel lblHorarioMiercoles;
    private javax.swing.JLabel lblHorarioViernes;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblInaugusarioLunes;
    private javax.swing.JLabel lblInfoPortada;
    private javax.swing.JLabel lblLugarPortada;
    private javax.swing.JPanel pnCabecera;
    private javax.swing.JPanel pnCuerpo;
    private javax.swing.JPanel pnJueves;
    private javax.swing.JPanel pnLunes;
    private javax.swing.JPanel pnMartes;
    private javax.swing.JPanel pnMiercoles;
    private javax.swing.JPanel pnPiePagina;
    private javax.swing.JPanel pnPortada;
    private javax.swing.JPanel pnViernes;
    // End of variables declaration//GEN-END:variables
}
